<<<<<<< HEAD
name: Test React App
on: push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install Node
        run: npm ci
      - name: Test application
        run: npm run test
=======
>>>>>>> 208498eb0ddd2214a3b07ead80e0689a7fac8856
